version: '3.9'

services:
  user-management:
    build:
      context: .
      dockerfile: deployments/user-management/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://user:password@db:5432/tirigo?sslmode=disable
      - REDIS_ADDR=redis:6379
      - JWT_SECRET=my_secret_key
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tirigo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  postgres_test_data:
