version: '3.9'

services:
  user-management:
    build:
      context: .
      dockerfile: deployments/user-management/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USER_DATABASE=postgres://user:password@db:5432/tirigo?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tirigo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
